definitions:
  auth.authResponse:
    properties:
      expire:
        type: string
      token:
        type: string
    type: object
  auth.login:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.CreateRequest:
    properties:
      anchor:
        description: 主播id
        example: 主播userId
        type: string
      anchor_nick:
        description: 主播Nick
        example: 主播nick
        type: string
      extends:
        description: 扩展字段，通常是JSON格式字符串
        example: 扩展字段，通常是JSON格式字符串
        type: string
      mode:
        default: 0
        description: 模式，默认0 普通直播，1 连麦直播
        example: 0
        type: integer
      notice:
        description: 直播公告
        example: 直播公告
        type: string
      title:
        description: 直播标题
        example: 直播标题
        type: string
    required:
    - anchor
    - anchor_nick
    - title
    type: object
  handler.DeleteRequest:
    properties:
      id:
        example: uuid，直播房间id
        type: string
      user_id:
        example: 当前用户id
        type: string
    required:
    - id
    - user_id
    type: object
  handler.GetRequest:
    properties:
      id:
        example: uuid，直播房间id
        type: string
      user_id:
        example: 当前用户id
        type: string
    required:
    - id
    - user_id
    type: object
  handler.ListRequest:
    properties:
      page_num:
        example: 1
        type: integer
      page_size:
        example: 10
        type: integer
      user_id:
        type: string
    required:
    - page_num
    - page_size
    - user_id
    type: object
  handler.LiveStatusRequest:
    properties:
      id:
        example: uuid，直播房间id
        type: string
      user_id:
        example: 当前用户id
        type: string
    required:
    - id
    - user_id
    type: object
  handler.TokenRequest:
    properties:
      device_id:
        example: 设备id：DEVICE-ID
        type: string
      device_type:
        example: 设备类型：android/ios/web/win/mac
        type: string
      user_id:
        example: 用户id:foo
        type: string
    required:
    - device_id
    - device_type
    - user_id
    type: object
  handler.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.UpdateRequest:
    properties:
      extends:
        description: 扩展字段，通常是JSON格式字符串
        example: 扩展字段，通常是JSON格式字符串
        type: string
      id:
        example: uuid，可以是消息组id
        type: string
      notice:
        description: 直播公告
        example: 直播公告
        type: string
      title:
        description: 直播标题
        example: 直播标题
        type: string
    type: object
  live.PullLiveInfo:
    properties:
      flv_url:
        type: string
      hls_url:
        type: string
      rtmp_url:
        type: string
      rts_url:
        type: string
    type: object
  models.LinkInfo:
    properties:
      cdn_pull_info:
        $ref: '#/definitions/live.PullLiveInfo'
        description: 普通观众CDN拉流地址
      rtc_pull_url:
        description: 拉流地址
        type: string
      rtc_push_url:
        description: 推流地址
        type: string
    type: object
  models.Metrics:
    properties:
      like_count:
        type: integer
      online_count:
        type: integer
      pv:
        type: integer
      uv:
        type: integer
    type: object
  models.PushLiveInfo:
    properties:
      rtmp_url:
        type: string
      rts_url:
        type: string
      srt_url:
        type: string
    type: object
  models.RoomInfo:
    properties:
      anchor_id:
        description: 主播Id
        type: string
      anchor_nick:
        description: 主播Nick
        type: string
      chat_id:
        description: 群组Id
        type: string
      cover_url:
        description: 直播封面
        type: string
      created_at:
        description: 创建时间
        type: string
      extends:
        description: 扩展字段
        type: string
      id:
        description: 直播Id
        type: string
      link_info:
        $ref: '#/definitions/models.LinkInfo'
        description: 连麦PK 等信息， 动态生成
      meeting_id:
        description: 连麦Id
        type: string
      metrics:
        $ref: '#/definitions/models.Metrics'
        description: 直播间统计
      mode:
        description: 直播模式 0-普通直播, 1-连麦直播，2-PK直播
        type: integer
      notice:
        description: 直播公告
        type: string
      pull_url_info:
        $ref: '#/definitions/live.PullLiveInfo'
        description: 拉流相关地址信息，动态生成
      push_url_info:
        $ref: '#/definitions/models.PushLiveInfo'
        description: 推流相关地址信息，动态生成
      status:
        description: 直播状态，0-准备中，1-已开始，2-已结束
        type: integer
      title:
        description: 直播标题
        type: string
      updated_at:
        description: 更新时间
        type: string
      user_status:
        $ref: '#/definitions/models.UserStatus'
        description: 用户状态
    type: object
  models.Status:
    properties:
      code:
        type: integer
      details: {}
      message:
        type: string
    type: object
  models.UserStatus:
    properties:
      mute:
        type: boolean
      mute_source:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /create:
    post:
      consumes:
      - application/json
      description: 创建直播房间
      operationId: create
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 创建直播房间
  /delete:
    post:
      consumes:
      - application/json
      description: 删除房间
      operationId: delete
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 删除房间
  /get:
    post:
      consumes:
      - application/json
      description: 获取直播房间详情
      operationId: get
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.GetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 获取直播房间详情
  /list:
    post:
      consumes:
      - application/json
      description: 获取直播房间列表
      operationId: list
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.ListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.RoomInfo'
            type: array
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 获取直播房间列表
  /login:
    post:
      consumes:
      - application/json
      description: App用户登陆
      operationId: login
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.login'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/auth.authResponse'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      summary: App用户登陆
  /pause:
    post:
      consumes:
      - application/json
      description: 暂停直播
      operationId: pause
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LiveStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 暂停直播
  /start:
    post:
      consumes:
      - application/json
      description: 开始直播
      operationId: start
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LiveStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 开始直播
  /stop:
    post:
      consumes:
      - application/json
      description: 停止直播
      operationId: stop
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LiveStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 停止直播
  /token:
    post:
      consumes:
      - application/json
      description: 获取token
      operationId: token
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 获取TOKEN
  /update:
    post:
      consumes:
      - application/json
      description: 更新房间详情
      operationId: update
      parameters:
      - description: Bearer your-token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.RoomInfo'
        "400":
          description: 4xx, 客户端错误
          schema:
            $ref: '#/definitions/models.Status'
        "500":
          description: 5xx, 请求失败
          schema:
            $ref: '#/definitions/models.Status'
      security:
      - ApiKeyAuth: []
      summary: 更新房间详情
swagger: "2.0"
